export interface UserData {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  roles: string[];
  phoneNumber: string;
  dateJoined?: string;    // e.g., "2026-01-19"
  memberType?: string;    // e.g., "Premium", "Basic"
  instagram?: string;
  twitter?: string;
  github?: string;
  facebook?: string;
  threads?: string;
  status?: string;        // e.g., "Online", "Offline"
  avatarId?: string;      // <-- added avatarId
}

// You can add more users here easily
export const users: UserData[] = [
  {
    id: "1",
    firstName: "Mahesa",
    lastName: "Rafiansyah",
    email: "mahesa@example.com",
    password: "MahesaMita",
    roles: ["Administrator"],
    phoneNumber: "+62 812-3456-7890",
    dateJoined: "2023-01-01",
    memberType: "Premium",
    instagram: "@mahesa",
    twitter: "@mahesa",
    github: "mahesaGH",
    facebook: "mahesaFB",
    threads: "@mahesaThreads",
    status: "Online",
    avatarId: "00",
  },
  {
    id: "2",
    firstName: "Sara",
    lastName: "Tan",
    email: "sara@example.com",
    password: "pass123",
    roles: ["Support"],
    phoneNumber: "+62 811-2222-3333",
    dateJoined: "2024-03-15",
    memberType: "Basic",
    instagram: "@sara",
    twitter: "@sara",
    github: "saraGH",
    facebook: "saraFB",
    threads: "@saraThreads",
    status: "Offline",
    avatarId: "01",
  },
  {
    id: "3",
    firstName: "Michelle",
    lastName: "Aurelia",
    email: "michelle@example.com",
    password: "michellePass",
    roles: ["Finance"],
    phoneNumber: "+62 813-9988-1122",
    dateJoined: "2022-07-20",
    memberType: "Premium",
    instagram: "@michelle",
    twitter: "@michelle",
    github: "michelleGH",
    facebook: "michelleFB",
    threads: "@michelleThreads",
    status: "Online",
    avatarId: "02",
  },
  {
    id: "4",
    firstName: "Rara",
    lastName: "Sundari",
    email: "rara@example.com",
    password: "raraCute",
    roles: ["HR"],
    phoneNumber: "+62 815-6677-2211",
    dateJoined: "2023-06-10",
    memberType: "Basic",
    instagram: "@rara",
    twitter: "@rara",
    github: "raraGH",
    facebook: "raraFB",
    threads: "@raraThreads",
    status: "Offline",
    avatarId: "03",
  },
  {
    id: "5",
    firstName: "Nina",
    lastName: "Hartati",
    email: "nina@example.com",
    password: "ninaSecure",
    roles: ["Support"],
    phoneNumber: "+62 819-5544-7788",
    dateJoined: "2024-01-05",
    memberType: "Premium",
    instagram: "@nina",
    twitter: "@nina",
    github: "ninaGH",
    facebook: "ninaFB",
    threads: "@ninaThreads",
    status: "Online",
    avatarId: "04",
  },
  {
    id: "6",
    firstName: "Lina",
    lastName: "Wijaya",
    email: "lina@example.com",
    password: "linaStrong",
    roles: ["Marketing"],
    phoneNumber: "+62 817-4400-2233",
    dateJoined: "2022-11-12",
    memberType: "Basic",
    instagram: "@lina",
    twitter: "@lina",
    github: "linaGH",
    facebook: "linaFB",
    threads: "@linaThreads",
    status: "Offline",
    avatarId: "05",
  },
  {
    id: "7",
    firstName: "Johan",
    lastName: "Pratama",
    email: "johan@example.com",
    password: "johanPass",
    roles: ["Administrator"],
    phoneNumber: "+62 812-9900-5566",
    dateJoined: "2021-12-01",
    memberType: "Premium",
    instagram: "@johan",
    twitter: "@johan",
    github: "johanGH",
    facebook: "johanFB",
    threads: "@johanThreads",
    status: "Online",
    avatarId: "06",
  },
  {
    id: "8",
    firstName: "Kevin",
    lastName: "Hartono",
    email: "kevin@example.com",
    password: "kevinSecure",
    roles: ["Developer"],
    phoneNumber: "+62 818-2211-9944",
    dateJoined: "2023-08-22",
    memberType: "Premium",
    instagram: "@kevin",
    twitter: "@kevin",
    github: "kevinGH",
    facebook: "kevinFB",
    threads: "@kevinThreads",
    status: "Online",
    avatarId: "07",
  },
];
